name: CI/CD Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: ruff-action
        uses: astral-sh/ruff-action@v3.2.1

      - name: Print to console
        run: echo Hello GH Actions!
